const data = [
  {
    title: "Mobile Accessories",
    slug: "mobile-accessories",
    id: 1,
    img: "/images/categoriesImages/MobileAccessories.webp",
    badge: "Popular",
    description: "Cases, chargers, and essentials for every phone.",
  },
  {
    title: "Smart Gadgets",
    slug: "smart-gadgets",
    id: 2,
    img: "/images/categoriesImages/SmartGadgets.webp",
    badge: "Trending",
    description: "Smart home gear and connected devices for modern living.",
  },
  {
    title: "Computer Accessories",
    slug: "computer-accessories",
    id: 3,
    img: "/images/categoriesImages/ComputerAccessories.webp",
    badge: "Top picks",
    description: "Keyboards, mice, and desk upgrades for work and play.",
  },
  {
    title: "Home Electronics",
    slug: "home-electronics",
    id: 4,
    img: "/images/categoriesImages/HomeElectronics.webp",
    badge: "Best value",
    description: "Appliances and electronics to power your home.",
  },
  {
    title: "Books",
    slug: "books",
    id: 5,
    img: "/images/categoriesImages/Books.webp",
    badge: "Readers' choice",
    description: "Fiction, study guides, and bestsellers for every age.",
  },
  {
    title: "Stationery",
    slug: "stationery",
    id: 6,
    img: "/images/categoriesImages/Stationery.webp",
    badge: "Back to school",
    description: "Notebooks, pens, and supplies for office and study.",
  },
  {
    title: "Men's Weare",
    slug: "men-s-weare",
    id: 7,
    img: "/images/categoriesImages/MensWear.webp",
    badge: "New styles",
    description: "Everyday wear and seasonal looks for men.",
  },
  {
    title: "WoMen's Weare",
    slug: "women-s-weare",
    id: 8,
    img: "/images/categoriesImages/WomensWear.webp",
    badge: "Fresh drops",
    description: "Trend-led apparel and timeless wardrobe staples.",
  },
  {
    title: "Kids's Ware",
    slug: "kids-s-ware",
    id: 9,
    img: "/images/categoriesImages/KidsWear.webp",
    badge: "Family fave",
    description: "Comfortable, durable clothing for growing kids.",
  },
  {
    title: "Fashion Accessories",
    slug: "fashion-accessories",
    id: 10,
    img: "/images/categoriesImages/FashionAccessories.webp",
    badge: "Style edit",
    description: "Bags, watches, and accessories to finish your look.",
  },
];

export default data;
